sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
  - iojs
  - 6
  - 5
  - 4
  - 0.12.15
  - 0.11.16
  - 0.10.46
script:
  - gulp test --coverage
after_success:
  - npm run report-coverage
